### ISSUE TITLE
Add Custom Gates

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#145]
Add gates that utilise four wires and other custom gates

**Comment by CPerezz** [comment]
Could you continue the impl in a separate branch instead of doing in in `master`??

**Comment by decentralisedkev** [comment]
Hey Carlos, I gave this a good think.

I think it would be better to merge atomic PRs to master, instead of pushing all features to a separate branch and merging that branch into master.

With the second method, I would need to keep the PR open for a long time, while I implement all of the custom gates. This would in turn mean that I would need to keep merging master into that branch and resolving conflicts.

With the first method, I would merge each atomic feature into master. Each PR would be open for a reasonable amount of time, and so I would only need to worry about one or two merge conflicts within that time.

I think your idea is good for a different context, for example, if me and you were working on an independent feature X that was isolated from the rest of the code, like external documentation. We could open a ‘docs’ branch and we would PR to that branch. When it is time to merge docs back into master, there should be no(little to none) merge conflicts as it was an isolated feature.

Even in this case, I think we would split up the job of docs into atomic PRs and merge each PR into master, unless there was a valid reason to branch off; maybe a large team? This is because the cognitive load of multiple PRs which adds small features is less than one massive PR which adds a bunch of features as there is less lines of code and most likely a more focussed goal to the PR.

In our case, custom gates is not an isolated feature and so it would probably be better to to merge atomic PRs into master gradually until the issue is closed. Where an atomic feature in this case would be a custom gate (eg range_gate or XOR_gate).

WDYT? Let me know if anything sounds off in what I said

**Comment by CPerezz** [comment]
> WDYT? Let me know if anything sounds off in what I said

It's fine, just please request reviews on each PR so I can manage mines also!

**Comment by decentralisedkev** [comment]
> > WDYT? Let me know if anything sounds off in what I said
> 
> It's fine, just please request reviews on each PR so I can manage mines also!

You mean request reviews, so you can be notified about it and manage your own PR?

**Comment by CPerezz** [comment]
Not that, since I can just watch the repo. But on this way we can discuss the new implementations you're doing each time you make additions. So it's easier to handle the impl direction.

**Comment by kevaundray** [comment]
Closing since the custom gates are now implemented, except for the ECC-Gate. Will open another issue for it
