### ISSUE TITLE
Decouple prover from `composer.preprocess`

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/plonk#186]
This code snippet passes:

```rust
use bls12_381::Scalar;
use merlin::Transcript;
use plonk::commitment_scheme::kzg10::PublicParameters;
use plonk::constraint_system::standard::{Composer, StandardComposer};
use plonk::fft::EvaluationDomain;

fn main() {
    fn new_composer() -> (StandardComposer, Vec<Scalar>) {
        let mut composer = StandardComposer::new();
        let pi = vec![];

        composer.add_dummy_constraints();
        composer.add_dummy_constraints();
        composer.add_dummy_constraints();

        (composer, pi)
    }

    const CAPACITY: usize = 1024;
    let public_parameters = PublicParameters::setup(CAPACITY, &mut rand::thread_rng()).unwrap();

    let (ck, vk) = public_parameters.trim(CAPACITY).unwrap();
    let domain = EvaluationDomain::new(CAPACITY).unwrap();

    // Preprocess circuit
    let mut composer = new_composer().0;
    let mut transcript = Transcript::new(b"hades-gadget-test");
    let circuit = composer.preprocess(&ck, &mut transcript, &domain);

    // Prove
    let (mut composer, pi) = new_composer();
    let proof_circuit = composer.preprocess(&ck, &mut transcript, &domain);
    let proof = composer.prove(&ck, &proof_circuit, &mut transcript.clone());

    // Verify
    assert!(proof.verify(&circuit, &mut transcript.clone(), &vk, pi.as_slice()));
}
```

But it will fail if we change the prover for
```rust
    // Prove
    let (mut composer, pi) = new_composer();
    let proof = composer.prove(&ck, &circuit, &mut transcript.clone());
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/permutation/permutation.rs:403:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The prover perspective should not be forced to call `composer.preprocess`

**Comment by CPerezz** [comment]
It is not forced.
Indeed you can grab a previously pre-processed `PreProcessedCircuit` and commit your witness with it by calling `composer.prove()`

I'm not sure I'm following you @vlopes11  . SInce you talk about performance regression on the title but then you show that it fails..

**Comment by CPerezz** [comment]
@kevaundray , what @vlopes11 is saying here is that the `Prover` does not have the capability of using a previously pre-processed `PreProcessedCircuit` to build his proofs.

I think this is not true.

Your code does not compile because the second composer is not commiting any witnesses.

You don't need to call `PreProcess` but you do need to call:
```
composer.add_dummy_constraints();
        composer.add_dummy_constraints();
        composer.add_dummy_constraints();
```
Can you verify it @kevaundray ?

**Comment by CPerezz** [comment]
After discussing this yesterday on a call with @vlopes11 , we added my suggestion and this problem is solved. So this issue regarding the decoupling can be closed.

Anyway, there's another issue which is related to the `add_gate` and `big_add_gate` which is blocking https://github.com/dusk-network/Hades252/issues/43
