### ISSUE TITLE
TRACKING ISSUE -> Plookup implementation

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#236]
As we know, Aztec guys are finishing their work on plookup. 

It would be nice to wait until we see if they're able to avoid having an extra commitment that turns on plookup.

Once this is done and they have that stabilized. We absolutely need to implement it inside of our repo since it improves drastically the gate-number needed by a lot of custom gates.

**Comment by ndbunner** [comment]
Hi, I work at [Metastate](https://metastate.dev), and we're also interested in having a rust implementation of plonk/plookup, so we'd like to talk about taking this on. Also, part of our plan for this is addressing issue #239 so we can use the same code for all the grand product arguments involved.

**Comment by ndbunner** [comment]
Commenting to add a bit of an overview for how we're thinking about implementing this. For now we've been considering only lookup gates implementing a binary operation, so @kevaundray 's plookup implementation is another good starting point. Here are the changes we'd plan to make to combine them (though they're all up for discussion):

In the plonk code:
We do want to refactor the permutation module, due to the number of accumulator arguments in other areas of the combined protocol. A smaller tweak is that we'd need to add a selector wire for lookup gates. We'd also incorporate a check that the lookup compressions are done correctly as part of the input/output gate behavior check.

In the plookup code:
We'd replace [concatenate_and_sort](https://github.com/kevaundray/plookup/blob/2b34b0b4d5b19aafb07323476dd510e8a0488224/src/multiset/multiset.rs#L53) with a new sorting function that will also output the permutation &rho; so that we can create a proof that the sorted lookups are indeed a rearrangement. Though we do want to avoid having an extra wire devoted solely to lookups, and our thoughts on how to do that are [here](https://www.plonk.cafe/t/strategies-for-integrating-plookup-with-plonk/36/3?u=ndbunner). Since both the rearrangement argument and the main plookup argument use a grand product/accumulator argument, we think it's worth refactoring the permutation module in the plonk code so all three arguments can use the same code.

**Comment by CPerezz** [comment]
Hi @ndbunner sorry for the late reply.

I think it might be easier to discuss the collaboration and the ideas you have by mail so that we don't pollute the issue. 
You should have received a mail regarding that.

Hope to hear from you.

Cheers,
Carlos.

**Comment by CPerezz** [comment]
Closing this since it's being actively developed and has many issues/PR's now.
