### ISSUE TITLE
Add source code for benchmark

### ISSUE THREAD

**Issue by juchiast** [dusk-network/plonk#252]
Hello Dusk team, thank you for providing a public implementation of the protocol. Can you add the source code for the mentioned benchmark in README? This would help a lot with running the crate and comparing with other protocols. Thank you!

**Comment by CPerezz** [comment]
Hey thanks for your input!

It would be quite simple to do it. We've plans to add more explicit & descriptive benchmarks in the repo, but we've been quite busy with other libraries.

This would be a two step process. 

First of all, you should generate a `PreProcessedCircuit` with the circuit you want to have (it can be dummy using `composer.add_dummy_constraints` repeatedly until you get your desired circuit size.

Then, just benchmark the `composer.prove()` call, since you want to just bench the proving times, not the preprocessing ones.

We will eventually come back to this and implement more explicit benchmarks. For now, what I would suggest to you is to take that approach also using the docs in https://github.com/dusk-network/plonk/tree/v0.1.0/examples.
Specifically examples 3_0 & 3_1.

**Comment by CPerezz** [comment]
Closed since we already have to solve #317 first.
