### ISSUE TITLE
Implement `pow_of_two` for Scalar

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#259]
Since I start to see few places where we use this, what about having:

```rust
self.variables[&a] & Scalar::pow_of_2(num_bits) - Scalar::one(),
```

instead?
Not only it's more concise and readable, but the implementation can remove the unnecessary iteration and the array of four `u64` creation in the stack since we just pass a single value (`usize` I assume).

_Originally posted by @ZER0 in https://github.com/dusk-network/plonk/pull/258_

**Comment by kevaundray** [comment]
- This seems to imply a new associated function on Scalar. Could you explain why this issue was raised in PLONK and not the bls repo? 
- self.variables is a hashmap `HashMap<Variable, Scalar>` on the composer. I'm guessing it should be Scalar & Scalar, as Variable & Scalar would not be possible. Maybe you could clarify here?

**Comment by CPerezz** [comment]
As @kevaundray correctly stated, this is not the correct repo to open the issue. I'll move it.
