### ISSUE TITLE
Scalar multiplication - Verification fails for different point

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/plonk#276]
The following pseudo code will fail:
```
A := a · G
B := b · G

prover_circuit {
  scalar_mul(a, B)
}

verifier_circuit {
  scalar_mul(0, A)
}
```
And the following will work
```
A := a · G
B := b · G

prover_circuit {
  scalar_mul(a, B)
}

verifier_circuit {
  scalar_mul(0, B)
}
```

We need to find a way to workaround this issue in order to perform diffie-hellman key exchange.

Here follows an example in Rust on how to reproduce the error:
```rust
use dusk_plonk::constraint_system::ecc;
use dusk_plonk::jubjub::{ExtendedPoint, GENERATOR};
use dusk_plonk::prelude::*;

use std::ops::Mul;

fn main() {
    let mut rng = rand::thread_rng();

    let bob_secret = JubJubScalar::random(&mut rng);
    let bob_public = GENERATOR.to_niels().mul(&bob_secret);

    let alice_secret = JubJubScalar::random(&mut rng);
    let alice_public = GENERATOR.to_niels().mul(&alice_secret);

    let pp = PublicParameters::setup(1 << 9, &mut rng).unwrap();
    let (ck, vk) = pp.trim(1 << 9).unwrap();

    let label = b"some-label";

    let circuit = |composer: &mut StandardComposer, secret: JubJubScalar, public: ExtendedPoint| {
        let secret = composer.add_input((secret).into());
        ecc::scalar_mul(composer, secret, public);

        composer.add_dummy_constraints();
    };

    let mut prover = Prover::new(label);
    circuit(prover.mut_cs(), alice_secret, bob_public);
    prover
        .preprocess(&ck)
        .expect("Error on preprocessing stage");
    let proof = prover.prove(&ck).expect("Error in proof generation stage");

    let mut verifier = Verifier::new(label);

    // The reason for the failure is here
    // It will not happen if we pass `bob_public` to `circuit`
    // 
    // When the provers circuit was constructed with `bob_public`, it will not accept any other
    // point different than the initially provided
    circuit(verifier.mut_cs(), JubJubScalar::zero(), alice_public);

    verifier
        .preprocess(&ck)
        .expect("Error on preprocessing stage");

    assert!(verifier
        .verify(&proof, &vk, &vec![BlsScalar::zero()])
        .is_ok())
}
```

**Comment by CPerezz** [comment]
AFAIK @kevaundray, @Bounce23 and @khovratovich will be researching on this topic to try to come up with a solution for the `var_base_msm` inside of PLONK circuits. 

This will become the tracking issue, and appart of a solution as an implementation, a writeup about it will be needed and should be uploaded to our Gitbook docs.

**Comment by kevaundray** [comment]
**Clarification**

To clarify, this is the expected behaviour for the scalar multiplication gadget as the generator that is used is a part of the circuit description. This allows you to encode the checks into the quotient polynomial and use (currently) 256 gates for scalar multiplication. This will be reduced to 128 when JubJub returns base4 wnaf representations of scalars.
For the use-case of Pedersen commitments and preimage proofs, this is sufficient.  

Below I list the use-case which deviates from this, then some possible solutions depending on the context.  

**Use-Case**

The use-case IIUC is that we want to do a Diffie-Hellman Key exchange.

-  Alice(Prover) will input her secret key, Bob's public key and the shared key. Represent this as the  tuple (a, B, K)
-  Bob(Verifier) will input his secret key, Alice's public key and the shared key. Represent this as the following tuple (b, A, K)

-  Alice's circuit will create a proof that aB == K
-  Bob's circuit will create a proof that bA == K

_Note that K = aB = bA = abG . For some constant known generator G._

**Problem 1**

To reiterate the problem is that Alice and Bob have different circuits, because the second entry of the tuple is not the same for both the Prover and Verifier. This second entry is used in the circuit description, in order to optimise scalar multiplication, which as mentioned above fits the use-case for Pedersen commitments and fixed base scalar multiplication.

**Possible Solution To Problem 1 - use Inversion**

One possible solution is for Alice to compute the inverse of her private key, since knowing a private key also means you can compute the inverse.

- Alice(Prover) will input her secret key, the shared key and Bob's public key. Represent this as the following tuple (a_inv, K, B)
- Bob(Verifier) will input his secret key, the shared key and Alice's public key. Represent this as the following tuple (b_inv, K, A)

- Alice's circuit will prove that a_inv * K == B
- Bob's circuit will prove that b_inv * K == A

Since the second entry is the same, they both have the same circuit. However, depending on your use case this may not be suitable either. Below I list a problem depending on the use-case.

**Problem 2** 

If the second entry in the tuple changes, then the circuit changes. This would not allow you to have a single circuit for arbitrary points. So if the shared key changes for the same circuit, then this solution will not be suitable for the intended use-case.

**Possible Solution to Problem 2 - Add more custom gates**

It is possible to do scalar multiplication over any arbitrary base, but it will cost a lot of gates to make the correct checks. 

The main checks that need to be completed are:

- Scalar decomposition
- Curve Addition
- Curve Doubling

You could pack these checks into three new custom gates.

**Notes - Add more custom gates**

- This is assuming double-and-add for scalar multiplication, for variable base. I'm not sure it would be beneficial to add pre-computations since it would need to be done per proof.  

- We are using Edwards Curve, so we could just have a point addition gate, since the curve addition check is done in the quotient polynomial.

- Adding three more gates, adds to the proof size and the Prover work.

**Summary**

There seems to be a trade-off between flexibility and optimisation. In the current scalar multiplication gate implementation, the Prover and Verifier must supply the same list of Generators to the circuit. It's not very flexible in terms of input points, but allows for heavy optimisations since we can encode the Generators into the circuit and do the checks in the quotient polynomial. If you want your circuit to be flexible enough that the prover and verifier can supply arbitrary generators for a single circuit, then optimisations will need to be more general, such as optimising the scalar decomposition and curve arithmetic.
