### ISSUE TITLE
Re-add `add_constant_witness` method for the composer.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#280]
The method was removed in #278 and there were no issues/actions which support this.
See: https://github.com/dusk-network/plonk/commit/a8d8f3e143229e365baf8157418f94c99e4fbf1d#r41368517

The method was useful and is used across a lot of repos in the `v_0.2.6` so I think we should bring it back. Idk if it was an error or not, but definitely should still be in the codebase.

**Comment by kevaundray** [comment]
Hi, 

This method was introduced in https://github.com/dusk-network/plonk/commit/564e9695353758902b7ff63cc0d47417a2f4b21a

I believe this method is/will cause a bug;

- The method states that you are constraining a public input to a witness. However, it is constraining a selector polynomial value to the witness. 

- There is already an identical method named: `add_witness_to_circuit_description`which does the same thing.

The consequence of using `add_constant_witness` and believing that you are constraining public inputs, will be that each statement will create a new circuit. This is because selector polynomials define the circuit.

### Solution

If you need to constrain a public input, I suggest a new method called `constrain_public_input` or `add_public_input` or something more similar. Then exposing that instead.

**Comment by kevaundray** [comment]
Could you possibly link the places which were using this method, so that I can double check the usage later on?

**Comment by CPerezz** [comment]
The goal of the function is to reduce this verbosity: 
https://github.com/dusk-network/Poseidon252/blob/88169b39ccd36d017e08d7f5d94a8f7c82d5ca21/src/merkle_proof/proof.rs#L24
Or the most explicit case: https://github.com/dusk-network/Hades252/blob/7ba70c7b84504b9bc2df3e5c3ce8dbb8f02a3535/src/strategies/gadget.rs#L102

And instead have something like: 
https://github.com/dusk-network/plonk_gadgets/blob/b208fc49703e67170356ccd88a81a45ffbad9182/src/gadgets/scalar/scalar.rs#L38

**Comment by CPerezz** [comment]
@kevaundray was right and there's a method that does the exact same thing called: `add_witness_to_circuit_description` but it asks fora `variable` and a `Scalar` when it could just ask for a `Scalar` and return the `Variable`. So I'll create an issue in order to address that.
