### ISSUE TITLE
Public inputs error - Constrain to constant

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/plonk#306]
The follow snippet should pass:
```
use anyhow::{anyhow, Error};
use dusk_plonk::prelude::*;

const MAX_DEGREE: usize = 128;

fn gadget(composer: &mut StandardComposer) -> Result<Vec<BlsScalar>, Error> {
    let mut pi = vec![];

    let x = BlsScalar::one();
    let x = composer.add_input(x);

    pi.push(BlsScalar::zero());
    let z = composer.add(
        (BlsScalar::one(), x),
        (BlsScalar::one(), x),
        BlsScalar::zero(),
        BlsScalar::zero(),
    );

    // This won't pass
    pi.push(-BlsScalar::from(2u64));
    composer.constrain_to_constant(z, BlsScalar::zero(), -BlsScalar::from(2u64));

    // This will pass
    //pi.push(BlsScalar::zero());
    //composer.constrain_to_constant(z, BlsScalar::from(2u64), BlsScalar::zero());

    Ok(pi)
}

fn main() -> Result<(), Error> {
    let pub_params = PublicParameters::setup(MAX_DEGREE, &mut rand::thread_rng())?;
    let (ck, ok) = pub_params.trim(MAX_DEGREE)?;
    let label = b"some-label";

    let (pk, vk) = {
        let mut prover = Prover::new(label);
        let mut verifier = Verifier::new(label);

        gadget(prover.mut_cs())?;
        gadget(verifier.mut_cs())?;

        prover.preprocess(&ck)?;
        verifier.preprocess(&ck)?;

        let pk = prover
            .prover_key
            .ok_or(anyhow!("Prover key is missing after preprocessing!"))?;

        let vk = verifier
            .verifier_key
            .ok_or(anyhow!("Verifier key is missing after preprocessing!"))?;

        (pk, vk)
    };

    let mut prover = Prover::new(label);
    let pi = gadget(prover.mut_cs())?;
    prover.prover_key = Some(pk.clone());
    let proof = prover.prove(&ck)?;

    let mut verifier = Verifier::new(label);
    verifier.verifier_key = Some(vk.clone());
    verifier.verify(&proof, &ok, pi.as_slice())?;

    Ok(())
}
```

**Comment by CPerezz** [comment]
The reason this is not passing is that you can't simply push the PI into a vec and store them since the position 0 is indeed the third one in reality. 

When you generate a `Prover` or a `Verifier` they get charged with `dummy_constraints` to avoid errors such as committing to zero polynomials.

Therefore, that's why I added the `Circuit` trait and made some examples on how to use it.
The test passes when you constraint againts `q_c` selector polynomial but not when you do it against a PI since the order they have is not correct.

Indeed, if you do this:
```rust
let mut verifier = Verifier::new(label);
    verifier.verifier_key = Some(vk.clone());
    let pi = verifier.mut_cs().public_inputs.clone();
    verifier.verify(&proof, &ok, &pi)?;
```

It should work independently of how you constraint the variable.

My suggestion, use the [`Circuit` trait approach/example](https://github.com/dusk-network/plonk/blob/2626e5836d902a9e87c69a319ed10f4a11a941af/src/circuit_builder.rs#L113) or simply the solution I posted if you're not doing a "production" circuit.

I belive this can be closed since there's no issue with the PI, but check it by yourself and let me know!

**Comment by vlopes11** [comment]
We have only two gates; first the `StandardComposer::add` and second the `StandardComposer::constrain_to_constant`.

If I set `pi[5] = -BlsScalar::from(2u64)`, it works. But its weird that we have the first three public inputs set as zero without any related gates, no? The correct position should be `1` instead of `5`

**Comment by CPerezz** [comment]
I partially agree on that. But at the same time, add the dummy constraints at Prover/Verifier instanciation time guarantees that in the 100% of cases no one will experience issues with commiting to zero polynomials.

Also, no one is expected to play with the internals or to set the PI directly unless they know what they're doing.

**Comment by vlopes11** [comment]
So the answer is we have dummy constraints added to both `Prover` and `Verifier` on instantiation to avoid zeroed selector polynomials due to circuit misusage.

Got it.
