### ISSUE TITLE
cargo build error on branch v0.1.0 to run examples scripts

### ISSUE THREAD

**Issue by DreamWuGit** [dusk-network/plonk#321]
Hello, guys 
I am new to plonk project and rust language, studying it now
I saw https://github.com/dusk-network/plonk/tree/v0.1.0/examples   
I id like to run this examples , then git clone the code,  checkout to branch v0.1.0 and execute:  
cargo build   
meet error below 
![image](https://user-images.githubusercontent.com/16850793/98338815-ba939b00-2045-11eb-91c9-196dad59488b.png)

Note : on the master branch it is ok to build , but examples only exist in branch v0.1.0 from I see 
Can anybody give some instructions?

**Comment by CPerezz** [comment]
Hi @DreamWuGit .

There are a couple of things that look wrong here.
Looks to me that you haven't checked out correctly to `v0.1.0` branch since `canonical` dependency should not exist in release `v0.1.0`.

The steps that you should take to be able to run the tests are:
```
git clone https://github.com/dusk-network/plonk
git checkout  v0.1.0
cargo run --release --example _example_name_
```
You should get the outputs of the examples in the /examples/ folder. I just tried it and worked for me.


About the `min_const_generics`, you are getting the error probably because you're compiling `master` with 
the `stable` rust toolchain.
Please switch to the `nightly` toolchain by runing `rustup default nightly`(if you want it everywhere) or `rustup set override nightly` (if you only want nightly in this project folder).

**Comment by DreamWuGit** [comment]
rustup default nightly works for me !  Thanks!

**Comment by CPerezz** [comment]
Glad that it worked! :)

The examples can't work with the actual `master` since a lot of refactors have happened from `v0.1.0`.
The best example you can find to actually work with `master` with an easy example is located here: https://github.com/dusk-network/plonk/blob/f5b9427783c8f369efb95ee2fd0bbfe91d68862a/src/circuit_builder.rs#L175
It uses the `CircuitBuilder` which is the latest addition we've done to the repo, but all you really need is the `gadget` fn implemented for the trait. 

If you don't want to work with the `Circuit` abstraction then you can look to: https://github.com/dusk-network/plonk/blob/f5b9427783c8f369efb95ee2fd0bbfe91d68862a/src/constraint_system/helper.rs#L32 and it should give you the idea on how to basically prepare the env to work with the gadgets you design.

Closing this issue since it no longer applies.
If you need any other thing or something does not work, feel free to open another issue!
