### ISSUE TITLE
Remove Anyhow usage to make the crate's error handling `no_std` compatible

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#343]
Managing error handling in `no_std` crates that rely on `dusk-plonk` it's quite tough since all of the errors use `anyhow::Result` and `anyhow::Error`. This is a problem since `anyhow` always gets inclued and it's `no_std` version forces to include allocators which might not be desired. 

The idea is to create new types for the plonk errors that are no-std compatible and that impl display and other `std`-related stuff under a `std` flag.

**Comment by CPerezz** [comment]
You can implement Display now without the flag and we will add the flags once we introduce `alloc` and `std` features.

**Comment by burdges** [comment]
All true rust types know their size and alignment, which `dyn Trait` types accomplish using their vtable.  

In consequence, one could build a `TinyBox<T: Sized>` type that allocated when `size_of_val(&T) > size_of::<usize>()` but otherwise stored `T` internally, and then `TinyBox<dyn Trait>` could actually work correctly by using `size_of_val(&self)`, which only accesses the vtable, not the actual `self` data pointer. 

We could then make `TinyBox` work even without alloc, simply by making its non-alloc form panic when `size_of_val(&T) > size_of::<usize>()`.  

At this point, if one has a no_std compatable `Error` trait then one could rebuild the entire trait infrastructure of `std::io` on top of this trait.  This gives you `Result<T,dyn Error>` which works even without alloc for small enums, OS ernos, etc., but not large complex error types with backtrace allocations, etc.

I've zero time to implement this, but if anyone gets interested then I'm happy to give some pointers.  

cc https://github.com/rust-lang/project-error-handling/issues/20

**Comment by CPerezz** [comment]
I really like the idea @burdges . And also seems that there's work on the community towards a similar solution. 
I'll add an issue pointing to this message so that we can investigate further once we have more time (or if someone wants to work on it).

Thanks a lot for the suggestion and taking time to explain it, is really interesting! :smiley:
