### ISSUE TITLE
Understand and document the split of the polynomials for integrated plookup

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#344]
In PLONK, we take traditional polynomial interpolations from circuits circuits of size n and when we evaluate them we take 4n evaluations. Which is a quadrupling of the domain size. 

We need to understand the different domain sizes for different plookup polynomials so we can evaluate them correctly.

**Comment by EDGDrummond** [comment]
In the plonk code we increase the size of the domain by a factor of 4 when constructing the quotient polynomial. This is because we know the quotient polynomial will have a degree of up to 4n (where the original domain size is n). Thus in order to interpolate the values and extract the correct degree polynomial t, we need 4n (x,y) pairs that satisfy the equation.

Lastly we need to check how this extension effects the evaluation points obtained from the wire polynomials, e.g. w_L. For example we previously had n evaluation values for w_L, and now we have 4n evaluation values. The important thing we have to check is if the original n evaluation points are now spread equally in the 4n vector (i.e. with 3 values between each successive pair). This will determine which indices to take of the h_i polynomials to ensure plookup is integrated correctly.

**Comment by EDGDrummond** [comment]
The domain.rs file in the plonk library explains that the FFTs are done over domains of size 2^k for some k. Multiplying the domain size by a factor of 2 will have a relatively easily understood effect on how we have to manipulate the indices following the domain expansion.

Let's say we have h_1(i) = s_i and its 'next' element h_1(i+1) = s_{i+1}, and then we multiply the domain by 2. If we now do an FFT on h_1 we will evaluate the polynomial at 4n points rather than n, and the indices will be shifted accordingly. So now (abusing notation, treating h_1 as the FFT values rather than the polynomial it was) we have h_1(2i) = s_i and h_1(2i+2) = s_{i+1}.
