### ISSUE TITLE
404 error for `notes-pa` page

### ISSUE THREAD

**Issue by 3for** [dusk-network/plonk#415]
The page below is not accessible now, getting"404" error:
https://dusk-network.github.io/plonk/dusk_plonk/notes/prove_verify/notes-pa

**Comment by CPerezz** [comment]
Thanks for the catch!! 

@Bounce23 I think you wrote that. Could you please check wether there are docs for this and link them propperly or delete the reference?

If @3for you want to do so, feel free to.

**Comment by 3for** [comment]
I'm not so sure about the content in `notes-pa`.
Expecting our update.

**Comment by Bounce23** [comment]
Hi @3for, may I ask where you got this link from? Is it this [Github](https://github.com/dusk-network/plonk/blob/master/docs/notes-pa.md) or the [Crates.io](https://dusk-network.github.io/plonk/dusk_plonk/notes/prove_verify/index.html)? 
On both links though my computer, this works well. There is an issue to update the content [here](https://github.com/dusk-network/plonk/issues/194). The associated PR was closed due to a change in the permutation argument. 
I can re add it to a higher priority list with the revised Grand Permutation Argument.

**Comment by CPerezz** [comment]
Idk wether this is a prio or not TBH. We should maybe just remove the hyperlink to notes-pa since it doesn-t work @Bounce23 . It's impossible that it works since it gives a 404 and it's normal. It doesn't exist.

**Comment by 3for** [comment]
https://dusk-network.github.io/plonk/dusk_plonk/notes/prove_verify/index.html
![image](https://user-images.githubusercontent.com/30716372/110050941-dd358680-7d8f-11eb-82b8-d9d09a1c1105.png)

**Comment by CPerezz** [comment]
Yes @3for thanks for making it explicit! 

I already discussed it with @Bounce23 yesterday and showed him which was the place.

Thanks a lot for the catch!

**Comment by CPerezz** [comment]
Closed via #431
