### ISSUE TITLE
`make doc` failed

### ISSUE THREAD

**Issue by 3for** [dusk-network/plonk#465]
![image](https://user-images.githubusercontent.com/30716372/111072425-865d4900-8515-11eb-987e-f1afa948c45a.png)
Is there something incompatible with my rust version?
![image](https://user-images.githubusercontent.com/30716372/111072448-9d9c3680-8515-11eb-8c15-29fa80caae5c.png)

**Comment by CPerezz** [comment]
Hey @3for sorry. I didn't see the issue till now.. Apologies.

This is really weird since the `rustdoc::` prefix is something that was added on nightly-1.52. So you should not have any problems with this statement. 

Does this still happen? If so, could you double check that indeed you're with the latest nightly (now is 1.53 I think) and if it happens the same?

Thanks and sorry for the delay..

**Comment by 3for** [comment]
I use `rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)`, different errors occur:
<img width="575" alt="屏幕快照 2021-04-13 上午11 12 54" src="https://user-images.githubusercontent.com/30716372/114491479-450da580-9c49-11eb-84e4-428f20f11983.png">
