### ISSUE TITLE
Incorporate reduction of PLONK's next power of 2

### ISSUE THREAD

**Issue by EDGDrummond** [dusk-network/plonk#483]
PLONK can be made more efficient by altering the method used to achieve zero knowledge in some of the polynomials.

A couple of the polynomials can be defined slightly differently, and a couple of the checks can be altered to incorporate this efficiency.

- Update definition of the selector polynomials, and the permutation polynomial z
- Update the check involving the permutation polynomial (i.e. update the definition of the polynomial t)

**Comment by DreamWuGit** [comment]
is there any spec to describe what and why it improves @EDGDrummond ?

**Comment by Bounce23** [comment]
This issue was built on a misinterpreted premise. The domain of the FFT has to be a power of two. What this issue tackles is  their inner product argument, which in some cases requires polynomials of degree n-1 where n is a power of 2. So if you have a circuit, its size gets rounded up to n a power of 2, with degree n-1 polynomials, you the blinding factor and now have degree n+2 polynomials, which is bad because the inner product argument then has to treat them like degree 2n-1 polynomials (twice as large as they need to be).
