### ISSUE TITLE
Documentation not rendering math

### ISSUE THREAD

**Issue by ureeves** [dusk-network/plonk#567]
The equations and other math does not render in the "notes" part of the documentation. As an example take look at the current state of [docs.rs](https://docs.rs/dusk-plonk/0.8.1/dusk_plonk/notes/prove_verify/index.html).

**Comment by moCello** [comment]
Describe what you want implemented
Include Katex-html header in the generated docs

Describe "Why" this is needed
This is needed in order to render LaTeX correctly in the official documentation of our crate

Describe alternatives you've considered
Leave as is which means that the math in our documentation is unreadable

Additional context
N/A

**Comment by moCello** [comment]
Re-opening issue because LaTeX equations still don't render on docs.rs (they do locally). Inline LaTeX doesn't render both locally and on docs.rs.
