### ISSUE TITLE
Randomised Constraint system

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#83]
Similar to bulletproofs, it would be nice to have access to the randomisation available from the transcript.

Since we use Variables which are references to the actual values, it would be a different API

**Comment by CPerezz** [comment]
Well, we could use the RandomisedCS for the Verifier always, since it does not matter at all what he/she introduces inside the variables. 
Appart it would obviously be useful for the Prover when needs random variables.

For me the `StandardRandomisedCS` trait should be implemented on the same way as the `StandardComposer` but adding random `Fr`s on the circuit.

**Comment by CPerezz** [comment]
I would like to take this issue so I can kinda make the bases and discuss them with @decentralisedkev 

Seems more prio than #127 or the serde implementation for `PreprocessedCircuit` imo.
